export const CONTROL_INPUT = "CONTROL_INPUT";

export const SUBMIT_FORM = "SUBMIT_FORM";
export const SUBMIT_FAIL = "SUBMIT_FAIL";
export const SUBMIT_SUCCESS = "SUBMIT_SUCCESS";
export const INIT_SUBMIT_FORM = "INIT_SUBMIT_FORM";

export const PREPARE_DOWNLOAD = "INIT_DOWNLOAD";
export const INIT_DOWNLOAD = "INIT_DOWNLOAD";
export const DOWNLOAD_SUCCESS = "DOWNLOAD_SUCCESS";
export const DOWNLOAD_FAIL = "DOWNLOAD_FAIL";
export const DOWNLOAD = "DOWNLOAD";

export const EMPTY_FIELDS = "EMPTY_FIELDS";
export const FIELD_CHANGE = "FIELD_CHANGE";
export const BACKENDFIELD_ADD = "BACKENDFIELD_ADD";
export const BACKENDFIELD_REMOVE = "BACKENDFIELD_REMOVE";
export const BACKENDFIELD_SELECT_CHANGE = "BACKENDFIELD_SELECT_CHANGE";
export const BACKENDFIELD_CHANGE = "BACKENDFIELD_CHANGE";
export const CHECK_FORM_VALID = "CHECK_FORM_VALID";
